### ISSUE TITLE
Emacs >= 24.3.50: Callback is not called when stopping process!  Explicitly calling from timer.

### ISSUE THREAD

**Issue by tkf** [tkf/emacs-request#2]
Make sure the fix introduced by 7b1580f2959ba20b82d730874e1115999c3542a7 is fine.

**Comment by titaniumbones** [comment]
I don't quite undertand this bug. @syohex or @dochang can you please explain?

**Comment by titaniumbones** [comment]
closing as stale.

**Comment by matthew-piziak** [comment]
I think it's because otherwise you get a bunch of `REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.` errors.

**Comment by titaniumbones** [comment]
@matthew-piziak looks like a fix has been committed a ocuple of years ago htough ,is that right?

**Comment by matthew-piziak** [comment]
Possibly. I'm still getting it those messages on fresh Emacs and request versions though. Should I paste in some specific info?
